addons:
  ssh_known_hosts: 198.199.82.7
language: node_js
sudo: required
node_js:
- '0.12'
git:
  submodules: false
  depth: 2
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_a0116530697c_key -iv $encrypted_a0116530697c_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
- ./scripts/before_install.sh
install:
- npm install -g npm
- npm install
- npm prune
script:
- npm test && ./scripts/deploy.sh
notifications:
  email: false
env:
  global:
  - secure: IG50gM5ll3BpqYuCSOV+EztEeXpCURnyJ3fcXoi/eGD9gcvR3T5BLRBRSQb1t53/E+WdvqRbBDn4W+vEAtaquYRywtm6XAEH7++phwjS3dRdSFsnB62x9Bfn98+/TDjOxDrEGI/pwoNjOBmjfGQh0uBXGWqUOdnYQ2vYrklcQwS5ihC+AoK37YXy6hRfg7Jn2LnmBi72CMmcmt9he2Rr0v5lq/bwCaUCIzzpWeZZYcHCyMA7ylZUtI+a991Wn7QMgn0p7V/kbQ5Nbc/qNEjsPSqhxUdb0d0vxSycxTUvciZJddJhLcvVPeNP46+xS/1q7ZC0ipfw8NbL5RfsYBxzRPDdp+MtJTZy4sY7d+v8Dxc9U/BQtRS7pvH+NF8l0940ThiDBrWjZwtOkrrmaCDEVPcagosJsUcdnLnwMp2FdVxKOt/lDFRvOzTPqFSRP/3RmWaIbR5qZMuOd7BIKAr2h/htmf+R1J07ZIJSW96pVXvayxQMCWaYKmwDzKDyJeAYq1A+SEkuuFfO4chFGdVrdQDLPEkczpuCX1Jgrh3PPj0yVRy/v4MzDxdiZI1PH6W12xomVAkFA7tXgvne6+hZ1s7dEgTrh6hdYD5gizXTFPTbmlWf16OFGKUtcAhPDG2tB3pSy2/j1V+gAdUb23iPaJx3bDkF2sACD1SrTaj2bYE=
  - secure: EaTjiPku5SRK+UlBkEJ0ApSlPTjXvoYfZUfnDTXh4N4wmO8XyRX5nB3Sddy2rMtiJX8B8yXOxR8BBXsSc5G9TAnhPCWWxeJGRICQpH5yr4Z9nZRONU/otA3H4NT5BP9s502M8QHOUs/zP4jYjA1a3FrU0aJRhWyMCtXxBaWuPOcOcDWX+/5No0Vg4/bpgrXV7MCbSsfGnKEyUw5uXwWDwrcw4KVVwfgZveCu9vAIX9PP7FO0uMmkfHoyYhGyq0QSlyPMg9hRdkj0OVKzE5X+RuWRRjIjg9SE+QWGFSv2LWPc1t/hVV/Mt8tMxHsVBUilvANxM2o/IZDwJuKCqhQ0/2Rsdt3bN9iBH0nRv5wXsgXqUdK/KsdmWu+1uSlfu4i9su4tssGdKajugPJh/eMQGEsUX/eAgVGupLSbWKP2MFuzPRSDSu6bMJSINMGRSb7Ni/mAVGDrxhTz/N6rbJqKz/xJW2HLiSO5hAWiw0+VMqJYcWT+zPMyeUeTYI98EIGFS9d9LObEmkyR3LzY0pR0sobFvUVuUuX9p2YDFUAZTSI6Ouw8bNphu1dkzUR5PW0D49Y+w2lQkHnWdMImPvmUo7Hvx5MdBiH1my//23qyHZGBVMBDRgd+Q5zZyh3R3MpzUyJ6QhPGrIfL2cPDPodGs+v5aUz0+RVdK3kR42rN93A=
